### ISSUE TITLE
Uncaught Error: Class 'ZipArchive' not found

### ISSUE THREAD

**Issue by viktorix** [ClassicPress/directory#43]
Executing the new `wp dir update --id=xx` command throws an error.

```
Fatal error: Uncaught Error: Class 'ZipArchive' not found in /public_html/wp-content/mu-plugins/download-links.php:224
Stack trace:
#0 /public_html/wp-content/plugins/dir-cli/dir-cli.php(82): kts_maybe_update()
#1 [internal function]: XXSimoXX\dir\Dir->update()
#2 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(100): call_user_func()
#3 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}()
#4 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(491): call_user_func()
#5 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(419): WP_CLI\Dispatcher\Subcommand->invoke()
#6 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(442): WP_CLI\Runner->run_command()
#7 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1256): WP_CLI\Runner->run_command_and_exit()
#8 phar:///usr/local/bin/wp in /public_html/wp-content/mu-plugins/download-links.php on line 224
```

**Comment by viktorix** [comment]
zip was missing. Once installed, everything works.
